### ISSUE TITLE
Specify replication

### ISSUE THREAD

**Issue by konfiot** [storageos/helm-chart#21]
Hello,
I wondered : How can I specify replication with the helm chart, I want the sotrageOS deployment to have replication bu I only have found such explaination on baremetal or on docker, but not with kubernetes
Thanks a lot !

**Comment by Arau** [comment]
Hi @konfiot 

the replication is specified at the volume level. You can define any feature such as replication, throttling, compression, etc by setting the according label at the PVC. 

As an example, note the label `storageos.com/replicas: "1"` 

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-vol-1
  labels:
      storageos.com/replicas: "1"
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```

Thank you for the feedback. We will update the docs to make this clear.

**Comment by Arau** [comment]
Hi @konfiot,

If you are using k8s 1.10 with CSI enabled and the helm chart with CSI, you can specify features by default in the storage class definition. You just need to add a parameter. 

For instance, you can add labels such as `storageos.com/replicas: "1"` in the parameters section:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-label
parameters:
  fsType: ext4
  pool: default
  storageos.com/replicas: "1"
  somelabel2: somevalue2
provisioner: storageos
```

You can verify that your volumes are created with the labels using the StorageOS CLI. 
`storageos volume inspect your-vol-name`
